.nh
.TH "GTREE" "1" "Sep 2026" "gtree dev" "gtree Manual"

.SH NAME
.PP
gtree-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
.PP
\fBgtree completion [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for gtree for the specified shell.
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-c\fP, \fB--config\fP=""
	config file (default ~/.config/gtree/config.yml)

.PP
\fB-d\fP, \fB--depth\fP=0
	maximum recursion depth (0 = unlimited)

.PP
\fB--no-color\fP[=false]
	disable color output

.PP
\fB--only-dirty\fP[=false]
	hide clean repositories

.PP
\fB-s\fP, \fB--sort\fP=""
	sort order: dirty|recent|name (default from config)

.PP
\fB--watch\fP[=false]
	live-refreshing view (polls every few seconds)


.SH SEE ALSO
.PP
\fBgtree(1)\fP, \fBgtree-completion-bash(1)\fP, \fBgtree-completion-fish(1)\fP, \fBgtree-completion-powershell(1)\fP, \fBgtree-completion-zsh(1)\fP
