.nh
.TH "GTREE" "1" "Sep 2026" "gtree dev" "gtree Manual"

.SH NAME
.PP
gtree-completion-bash - Generate the autocompletion script for bash


.SH SYNOPSIS
.PP
\fBgtree completion bash\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for the bash shell.

.PP
This script depends on the 'bash-completion' package.
If it is not installed already, you can install it via your OS's package manager.

.PP
To load completions in your current shell session:

.EX
source <(gtree completion bash)

.EE

.PP
To load completions for every new session, execute once:

.SS Linux:
.EX
gtree completion bash > /etc/bash_completion.d/gtree

.EE

.SS macOS:
.EX
gtree completion bash > $(brew --prefix)/etc/bash_completion.d/gtree

.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for bash

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-c\fP, \fB--config\fP=""
	config file (default ~/.config/gtree/config.yml)

.PP
\fB-d\fP, \fB--depth\fP=0
	maximum recursion depth (0 = unlimited)

.PP
\fB--no-color\fP[=false]
	disable color output

.PP
\fB--only-dirty\fP[=false]
	hide clean repositories

.PP
\fB-s\fP, \fB--sort\fP=""
	sort order: dirty|recent|name (default from config)

.PP
\fB--watch\fP[=false]
	live-refreshing view (polls every few seconds)


.SH SEE ALSO
.PP
\fBgtree-completion(1)\fP
